# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Segmentation_Hybrid
                                 A QGIS plugin
 This plugin can be used to run segmentation lgorithms
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-17
        copyright            : (C) 2021 by Sravani D
        email                : sravanidvr@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Segmentation_Hybrid class from file Segmentation_Hybrid.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Segmentation_Hybrid import Segmentation_Hybrid
    return Segmentation_Hybrid(iface)
